#!/usr/bin/env bash
#
if [[ -r "$1" ]]; then
  payload="$(base64 <"$1")"
else
  payload="$1"
fi
function_name="$2"
response_file="$3"

( set -x -u ; aws lambda invoke --cli-read-timeout 240 --function "$function_name" --payload "$payload" "$response_file" )
