---
version: 2.1
jobs:
  lint_and_test_python:
    docker:
      - image: trussworks/circleci:29ab89fdada1f85c5d8fb685a2c71660f0c5f60c
    steps:
      - checkout
      - run:
          name: Install build & test dependencies
          command: |
            pip3 install --progress-bar off 'poetry==1.0.9' 'pre-commit==2.2.0'
      - run:
          name: Build & install
          command: poetry build && poetry install
      - run:
          name: Run pre-commit hooks on all files
          command: pre-commit run --all-files --show-diff-on-failure
      - run:
          name: Run tests
          command: |
            poetry run pytest --full-trace
      - store_artifacts:
          path: dist
workflows:
  version: 2.1
  pipeline:
    jobs:
      - lint_and_test_python
