jobs:
  lint_and_test_python:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:bb3bffc3e3a69473458103e53873f1bcce6ffc5b
    steps:
    - checkout
    - run:
        command: 'pip3 install --progress-bar off ''poetry==1.0.9'' ''pre-commit==2.2.0''

          '
        name: Install build & test dependencies
    - run:
        command: poetry build && poetry install
        name: Build & install
    - run:
        command: pre-commit run --all-files --show-diff-on-failure
        name: Run pre-commit hooks on all files
    - run:
        command: 'poetry run pytest --full-trace

          '
        name: Run tests
    - store_artifacts:
        path: dist
version: 2.1
workflows:
  pipeline:
    jobs:
    - lint_and_test_python:
        context:
        - org-global
  version: 2.1
